//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeImp.Gluon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeImp.Gluon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Curve {
            get {
                object obj = ResourceManager.GetObject("Curve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diskstructure {
            get {
                object obj = ResourceManager.GetObject("diskstructure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Verdana, Arial, sans-serif;
        ///				font-size: 1.2em;
        ///			}
        ///			
        ///			a
        ///			{
        ///				text-decoration: none;
        ///				color: black;
        ///			}
        ///			
        ///			a:hover
        ///			{
        ///				text-decoration: none;
        ///				color: black;
        ///			}
        ///		&lt;/style&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;SCRIPT language=&quot;JavaScript&quot;&gt;
        ///			function bcolor(e)
        ///			{
        ///				if((e.style.backgroundColor != &apos;#ffffff&apos;) &amp;&amp; (e.style.backgroundColor != &apos;ffffff&apos;) &amp;&amp; (e.style.backgroundColor != &apos;white&apos;))
        ///				{
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grocerieshtml {
            get {
                return ResourceManager.GetString("grocerieshtml", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap radarnoise {
            get {
                object obj = ResourceManager.GetObject("radarnoise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;margin: 0; padding: 0; background-color: black;&quot;&gt;
        ///&lt;object width=&quot;%width&quot; height=&quot;%height&quot;&gt;
        ///&lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/%id&amp;hl=en&amp;fs=1&amp;rel=0&amp;hd=1&amp;autoplay=1&amp;showinfo=0&amp;iv_load_policy=3&amp;color1=0x2b405b&amp;color2=0x9CADBA&amp;border=0&quot;&gt;&lt;/param&gt;
        ///&lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;
        ///&lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;
        ///&lt;embed src=&quot;http://www.youtube.com/v/%id&amp;hl=en&amp;fs=1&amp;rel=0&amp;hd=1&amp;autoplay=1&amp;showinfo=0&amp;iv_load_policy=3&amp;color1=0x2b405b&amp;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string youtubehtml {
            get {
                return ResourceManager.GetString("youtubehtml", resourceCulture);
            }
        }
    }
}
